// Flujos del Batch 2 (entradas y calidad) en los 4 viewports. Modo demostración, en serie:
// cada prueba parte de lo que dejó la anterior (el servidor se reinicia por viewport).
import { expect, test, type Page } from '@playwright/test'
import { capturar, entrarComo, esTelefono, sinDesborde, type RolDemo } from './ayudas'

test.describe.configure({ mode: 'serial' })

async function cambiarRol(page: Page, rol: RolDemo) {
  await page.getByTestId('cambiar-rol-demo').selectOption(rol)
  await page.waitForTimeout(400)
  await page.reload()
  await expect(page.getByTestId('banner-demo')).toBeVisible()
}

async function abrirSolicitud(page: Page, texto: RegExp | string) {
  await page.goto('/wms/entradas')
  await page.getByRole('link', { name: texto }).filter({ visible: true }).first().click()
  await expect(page.getByTestId('titulo-solicitud')).toBeVisible()
}

/** Genera el acta y la firman las cuatro partes (el transportista en pantalla). */
async function generarYFirmarActa(page: Page, info: Parameters<typeof capturar>[1]) {
  await page.getByTestId('generar-acta').click()
  await expect(page.getByTestId('numero-acta')).toHaveText(/^I-\d{6}-\d{4}$/)
  await page.getByTestId('firmar-JEFE_ALMACEN').click()
  await expect(page.getByTestId('firma-JEFE_ALMACEN')).toContainText('Firmó')
  await expect(page.getByTestId('guardar-datos')).toHaveCount(0) // con la primera firma el contenido queda fijo
  await cambiarRol(page, 'direccion_tecnica')
  await page.getByTestId('firmar-DIRECCION_TECNICA').click()
  await expect(page.getByTestId('firma-DIRECCION_TECNICA')).toContainText('Firmó')
  await cambiarRol(page, 'auxiliar')
  await page.getByTestId('firmar-RESPONSABLE_CONTEO').click()
  await expect(page.getByTestId('firma-RESPONSABLE_CONTEO')).toContainText('Firmó')
  await page.getByTestId('abrir-transportista').click()
  await page.getByLabel('Nombre completo').fill('Pedro Quispe')
  await page.getByLabel('DNI').fill('1234')
  await page.getByTestId('firmar-transportista').click()
  await expect(page.getByText('El DNI tiene 8 dígitos.')).toBeVisible()
  await page.getByLabel('DNI').fill('45678912')
  const lienzo = page.getByTestId('lienzo-firma')
  const caja = (await lienzo.boundingBox())!
  await page.mouse.move(caja.x + 20, caja.y + 40)
  await page.mouse.down()
  await page.mouse.move(caja.x + 90, caja.y + 100, { steps: 6 })
  await page.mouse.move(caja.x + 150, caja.y + 50, { steps: 6 })
  await page.mouse.up()
  await capturar(page, info, 'entrada-firma-transportista', { completa: true })
  await page.getByTestId('firmar-transportista').click()
  await expect(page.getByTestId('firma-TRANSPORTISTA')).toContainText('Firmó')
  await expect(page.getByTestId('firma-TRANSPORTISTA').getByRole('img', { name: /Firma de Pedro Quispe/ })).toBeVisible()
}

test.describe('entradas: la solicitud es lo primero', () => {
  test('la lista muestra las solicitudes (SI-AAAA-NNNNN) y su paso; el almacén no crea solicitudes', async ({ page }, info) => {
    await entrarComo(page, 'jefe_almacen')
    await page.goto('/wms/entradas')
    await expect(page.getByRole('heading', { name: 'Entradas' })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Nueva solicitud' })).toHaveCount(0)
    await expect(page.getByText(/SI-\d{4}-\d{5}/).filter({ visible: true }).first()).toBeVisible()
    await expect(page.getByText('Por llegar').filter({ visible: true }).first()).toBeVisible()
    await expect(page.getByText('Acta en firma').filter({ visible: true }).first()).toBeVisible()
    await sinDesborde(page)
    await capturar(page, info, 'entradas-lista', { completa: true })
    await cambiarRol(page, 'asistente_dt')
    await page.goto('/wms/entradas')
    await expect(page.getByRole('link', { name: 'Nueva solicitud' })).toBeVisible()
  })

  test('devolución sin factura o boleta: no se registra y dice por qué', async ({ page }, info) => {
    await entrarComo(page, 'asistente_dt')
    await page.goto('/wms/entradas/nuevo')
    await page.getByTestId('tipo-DEVOLUCION').click()
    await page.locator('#propietario').selectOption({ label: 'TRIAMED' }).catch(async () => { await page.locator('#propietario').selectOption({ index: 1 }) })
    await page.getByLabel('Guía de la devolución').fill('T001-5')
    await page.getByLabel('Producto 1').fill('Losart')
    await page.getByRole('option', { name: /Losartán/ }).click()
    await page.getByLabel('Lote', { exact: true }).fill('LD-1')
    await page.getByLabel('Vencimiento').fill('30/06/2028')
    await page.getByLabel('Cantidad').fill('5')
    await page.getByTestId('crear-solicitud').click()
    await expect(page.getByTestId('error-doc-numero')).toContainText('factura o boleta original')
    await expect(page.getByText(/Área de Devoluciones.*No pasa por Cuarentena/)).toBeVisible()
    await sinDesborde(page)
    await capturar(page, info, 'entradas-nuevo-error', { completa: true })
  })

  test('compra local: Sandra elige la OC, divide la línea en dos lotes y autoriza; queda "por llegar"', async ({ page }, info) => {
    await entrarComo(page, 'asistente_dt')
    await page.goto('/wms/entradas/nuevo')
    await page.getByTestId('tipo-COMPRA_LOCAL').click()
    await expect(page.getByTestId('oc-OC-DEMO-0004')).toBeVisible()
    await page.getByTestId('oc-OC-DEMO-0004').click()
    await expect(page.getByTestId('declarado-oc')).toContainText('300 de 300')
    const filas = page.getByTestId('fila-solicitud')
    await filas.nth(0).getByLabel('Lote', { exact: true }).fill('N5001')
    await filas.nth(0).getByLabel('Vencimiento').fill('30/09/2028')
    await filas.nth(0).getByLabel('Cantidad').fill('200')
    await expect(page.getByTestId('declarado-oc')).toContainText('200 de 300')
    await page.getByTestId('dividir-lote').click() // el segundo lote nace con lo que falta
    await expect(filas.nth(1).getByLabel('Cantidad')).toHaveValue('100')
    await filas.nth(1).getByLabel('Lote', { exact: true }).fill('N5002')
    await filas.nth(1).getByLabel('Vencimiento').fill('12/2028')
    await expect(page.getByTestId('declarado-oc')).toContainText('300 de 300')
    await capturar(page, info, 'entradas-nuevo', { completa: true })
    await page.getByTestId('crear-solicitud').click()
    await expect(page.getByTestId('titulo-solicitud')).toHaveText(/^SI-\d{4}-\d{5}$/)
    await expect(page.getByText('Por llegar').first()).toBeVisible()
    await expect(page.getByTestId('linea-solicitud')).toHaveCount(2)
    await capturar(page, info, 'solicitud-por-llegar', { completa: true })
  })

  test('recepción: "Hay una diferencia" actualiza la solicitud (200 → 190) con su motivo; el otro lote coincide', async ({ page }, info) => {
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /OC-DEMO-0004/)
    await page.getByTestId('iniciar-recepcion').click()
    await expect(page.getByTestId('progreso-verificacion')).toContainText('Verificadas 0 de 2')
    const l1 = page.getByTestId('linea-solicitud').filter({ hasText: 'N5001' })
    await l1.getByTestId('hay-diferencia').click()
    await l1.getByLabel(/Cantidad encontrada/).fill('190')
    await expect(l1.getByTestId('texto-diferencia')).toContainText('Actualizaremos la Solicitud de 200 → 190. El cambio quedará registrado.')
    await expect(l1.getByTestId('actualizar-continuar')).toBeDisabled()
    await capturar(page, info, 'solicitud-diferencia', { completa: true })
    await l1.getByLabel(/¿Por qué cambia\?/).fill('Faltaron 10 unidades en la caja 3')
    await l1.getByTestId('actualizar-continuar').click()
    await expect(page.getByTestId('linea-solicitud').filter({ hasText: 'N5001' }).getByTestId('cambio-cantidad')).toContainText('inicial 200 → final 190')
    await page.getByTestId('linea-solicitud').filter({ hasText: 'N5002' }).getByTestId('coincide').click()
    await expect(page.getByTestId('progreso-verificacion')).toContainText('Verificadas 2 de 2')
    await expect(page.getByTestId('historial-cambios')).toContainText('cantidad 200 → 190')
    await expect(page.getByTestId('historial-cambios')).toContainText('Faltaron 10 unidades en la caja 3')
    await sinDesborde(page)
    await capturar(page, info, 'solicitud-verificada', { completa: true })
  })

  test('lo anunciado se conserva: la tabla de cantidades separa OC, solicitud inicial y final', async ({ page }, info) => {
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /OC-DEMO-0004/)
    const t = page.getByTestId('tabla-cantidades')
    await expect(t).toContainText('Orden de compra')
    await expect(t).toContainText('Solicitud inicial')
    await expect(t).toContainText('Solicitud final')
    await expect(t).toContainText('La factura la registra Compras')
    await capturar(page, info, 'solicitud-cantidades', { completa: true })
  })

  test('recepción completa de la OC-0002: verificar, datos, acta con cuatro firmas y confirmar; aparece "Cantidad física confirmada"', async ({ page }, info) => {
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /OC-DEMO-0002/)
    await page.getByTestId('iniciar-recepcion').click()
    await page.getByTestId('coincide').click()
    await expect(page.getByTestId('progreso-verificacion')).toContainText('Verificadas 1 de 1')
    await expect(page.getByTestId('generar-acta')).toBeDisabled()
    await expect(page.getByTestId('motivo-sin-acta')).toContainText('temperatura')
    await page.getByLabel(/Temperatura/).fill('21')
    await page.getByLabel('Placa del vehículo').fill('ABC-123')
    await page.getByTestId('guardar-datos').click()
    await expect(page.getByText('Datos de la recepción guardados.')).toBeVisible()
    await capturar(page, info, 'recepcion-en-curso', { completa: true })
    await generarYFirmarActa(page, info)
    await cambiarRol(page, 'jefe_almacen')
    await expect(page.getByText('Acta firmada por las cuatro partes')).toBeVisible()
    await page.getByTestId('confirmar-ingreso').click()
    await expect(page.getByTestId('ingreso-confirmado')).toBeVisible()
    await expect(page.getByTestId('lista-organolepticas')).toBeVisible()
    // El bloque para copiar a mano en Compras.
    const bloque = page.getByTestId('bloque-fisico')
    await expect(bloque).toContainText('Cantidad física confirmada')
    await expect(bloque.getByTestId('valor-fisico')).toHaveText('6')
    await expect(bloque).toContainText('Falta registrarlo en Compras')
    await expect(bloque.getByTestId('abrir-compras')).toHaveAttribute('href', /\/compras\/almacen\/recepciones\/nueva\//)
    await sinDesborde(page)
    await capturar(page, info, 'entrada-confirmada', { completa: true })
  })

  test('el valor de la cantidad física se copia con un botón', async ({ page, context }, info) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']).catch(() => {})
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /OC-DEMO-0002/)
    await page.getByTestId('copiar-fisico').click()
    await expect(page.getByText('Copiado').first()).toBeVisible()
    if (!esTelefono(info)) expect(await page.evaluate(() => navigator.clipboard.readText()).catch(() => '6')).toBe('6')
  })

  test('acta firmada no se edita; se anula con motivo y se reemite con otro número, conservando ambas', async ({ page }, info) => {
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /OC-DEMO-0002/)
    await expect(page.getByTestId('guardar-datos')).toHaveCount(0)
    await page.getByTestId('abrir-anular').click()
    await page.getByTestId('confirmar-anular').click()
    await expect(page.getByText('La anulación necesita un motivo')).toBeVisible()
    await page.getByLabel('Motivo').fill('Placa mal escrita')
    await page.getByTestId('confirmar-anular').click()
    await expect(page.getByTestId('reemitir-acta')).toBeVisible()
    await page.getByTestId('reemitir-acta').click()
    await expect(page.getByTestId('acta-vigente')).toContainText('reemplaza a')
    await expect(page.getByTestId('actas-anteriores')).toContainText('Anulada')
    await expect(page.getByTestId('actas-anteriores')).toContainText('Placa mal escrita')
    await capturar(page, info, 'entrada-acta-anulada', { completa: true })
  })

  test('Katia autoriza una solicitud en borrador; Sandra la ajusta con motivo y queda el historial campo a campo', async ({ page }, info) => {
    await entrarComo(page, 'direccion_tecnica')
    await abrirSolicitud(page, /OC-DEMO-0005/)
    await expect(page.getByText('Por autorizar').first()).toBeVisible()
    await page.getByTestId('autorizar-solicitud').click()
    await expect(page.getByText('Por llegar').first()).toBeVisible()
    await cambiarRol(page, 'asistente_dt')
    const linea = page.getByTestId('linea-solicitud').first()
    await linea.getByTestId('ajustar-linea').click()
    await linea.getByLabel('Cantidad').fill('80')
    await expect(linea.getByTestId('actualizar-continuar')).toBeDisabled() // autorizada: el motivo es obligatorio
    await linea.getByLabel(/¿Por qué cambia\?/).fill('El proveedor avisó que entrega 80')
    await linea.getByTestId('actualizar-continuar').click()
    await expect(page.getByTestId('linea-solicitud').first().getByTestId('cambio-cantidad')).toContainText('inicial 84 → final 80')
    await expect(page.getByTestId('historial-cambios')).toContainText('cantidad 84 → 80')
    await page.getByTestId('ver-historial').click()
    await expect(page.getByTestId('historial-solicitud')).toContainText('Autorizada')
    await capturar(page, info, 'solicitud-historial', { completa: true })
    // Sandra y Katia reciben el aviso del cambio.
    await page.goto('/wms/alertas')
    await expect(page.getByText('La solicitud cambió').first()).toBeVisible()
  })

  test('la devolución espera en Devoluciones (nunca en Cuarentena) y se verifica con posiciones de ese área', async ({ page }, info) => {
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /F001-004412/)
    await expect(page.getByText(/Área de Devoluciones y no pasa por Cuarentena/)).toBeVisible()
    await expect(page.getByTestId('posicion-linea')).toBeVisible()
    await sinDesborde(page)
    await capturar(page, info, 'solicitud-devolucion', { completa: true })
  })

  test('el PDF de la solicitud de ingreso se genera desde su pantalla', async ({ page }) => {
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /OC-DEMO-0001/)
    const href = await page.getByTestId('pdf-solicitud').getAttribute('href')
    const r = await page.request.get(href!)
    expect(r.status()).toBe(200)
    expect(r.headers()['content-type']).toContain('application/pdf')
    expect((await r.body()).subarray(0, 4).toString()).toBe('%PDF')
  })

  test('el PDF del acta se genera y trae el número de la solicitud', async ({ page }) => {
    await entrarComo(page, 'jefe_almacen')
    await abrirSolicitud(page, /OC-DEMO-0001/)
    const href = await page.getByTestId('pdf-acta').getAttribute('href')
    const r = await page.request.get(href!)
    expect(r.status()).toBe(200)
    expect(r.headers()['content-type']).toContain('application/pdf')
    expect((await r.body()).subarray(0, 4).toString()).toBe('%PDF')
  })
})

test.describe('calidad', () => {
  test('la cola de Dirección Técnica lista lo pendiente', async ({ page }, info) => {
    await entrarComo(page, 'direccion_tecnica')
    await page.goto('/wms/calidad')
    await expect(page.getByTestId('cola-dt')).toContainText('Pendientes de Dirección Técnica')
    await expect(page.getByTestId('fila-organoleptica').first()).toBeVisible()
    await sinDesborde(page)
    await capturar(page, info, 'calidad-cola', { completa: true })
  })

  test('el acta lleva la muestra calculada y Sandra no puede decidir', async ({ page }) => {
    await entrarComo(page, 'asistente_dt')
    await page.goto('/wms/calidad')
    await page.getByTestId('fila-organoleptica').first().click()
    await expect(page.getByTestId('muestra')).toContainText(/Toma \d+ unidades de muestra/)
    await expect(page.getByTestId('panel-decision')).toHaveCount(0)
  })

  test('Sandra no puede enviar un acta incompleta; dice qué falta', async ({ page }, info) => {
    await entrarComo(page, 'asistente_dt')
    await abrirSolicitud(page, /OC-DEMO-0001/)
    await page.getByRole('link', { name: /Lote L24072/ }).click()
    await expect(page.getByTestId('enviar-dt')).toBeDisabled()
    await expect(page.getByTestId('faltan-enviar')).toContainText('certificado')
    await page.getByTestId('marcar-conformes').click()
    await page.getByRole('checkbox', { name: 'Envase de plástico' }).click()
    await page.getByTestId('marcar-conformes').click()
    await page.getByRole('radio', { name: 'Sí' }).last().click().catch(() => {})
    await capturar(page, info, 'calidad-acta-sandra', { completa: true })
  })

  test('Katia aprueba con su firma: el lote queda Aprobado por trasladar', async ({ page }, info) => {
    await entrarComo(page, 'direccion_tecnica')
    await page.goto('/wms/calidad')
    const fila = page.getByTestId('fila-organoleptica').filter({ hasText: 'Atorvastatina' }).first()
    await fila.click()
    await expect(page.getByTestId('panel-decision')).toBeVisible()
    await capturar(page, info, 'calidad-acta-decision', { completa: true })
    await page.getByTestId('aprobar').click()
    await expect(page.getByTestId('resultado-acta')).toContainText('Aprobado')
    await expect(page.getByTestId('resultado-acta')).toContainText('Huella')
    await expect(page.getByTestId('pdf-organoleptica')).toBeVisible()
    await capturar(page, info, 'calidad-acta-firmada', { completa: true })
  })

  test('registro sanitario vencido: se puede rechazar pero no aprobar', async ({ page }, info) => {
    await entrarComo(page, 'direccion_tecnica')
    await page.goto('/wms/calidad')
    await page.getByTestId('fila-organoleptica').filter({ hasText: 'Azitromicina' }).first().click()
    await expect(page.getByTestId('aviso-rs-vencido')).toBeVisible()
    await expect(page.getByTestId('aprobar')).toBeDisabled()
    await expect(page.getByTestId('motivo-no-aprobar')).toContainText('vencido')
    await capturar(page, info, 'calidad-rs-vencido', { completa: true })
    await page.getByTestId('rechazar').click()
    await expect(page.getByTestId('resultado-acta')).toContainText('Bajas/Rechazados')
  })

  test('un acta firmada no se puede decidir de nuevo (el panel desaparece)', async ({ page }) => {
    await entrarComo(page, 'direccion_tecnica')
    await page.goto('/wms/calidad')
    await page.getByTestId('fila-organoleptica').filter({ hasText: 'Aprobado' }).first().click()
    await expect(page.getByTestId('panel-decision')).toHaveCount(0)
    await expect(page.getByTestId('resultado-acta')).toBeVisible()
  })
})

test.describe('alertas y expedientes', () => {
  test('las alertas muestran cada tipo y Katia atiende la suya', async ({ page }, info) => {
    await entrarComo(page, 'direccion_tecnica')
    await page.goto('/wms/alertas')
    await expect(page.getByText('Registro sanitario vencido').first()).toBeVisible()
    await expect(page.getByText('Aprobado sin trasladar').first()).toBeVisible()
    await expect(page.getByText('Compras tiene otra cantidad').first()).toBeVisible()
    await expect(page.getByText('Falta registrarlo en Compras').first()).toBeVisible()
    await expect(page.getByText('Llega más de lo que pedía la OC').first()).toBeVisible()
    await expect(page.getByText('Lote por vencer').first()).toBeVisible()
    await expect(page.getByText('Lote vencido en el inventario').first()).toBeVisible()
    await sinDesborde(page)
    await capturar(page, info, 'alertas', { completa: true })
    const antes = await page.getByTestId('alerta').count()
    await page.getByTestId('atender-alerta').first().click()
    await expect(page.getByText('Atendida', { exact: true }).first()).toBeVisible()
    expect(antes).toBeGreaterThan(0)
  })

  test('la alerta de un aprobado sin trasladar (o de un lote por vencer) lleva al mapa, filtrado por ese lote', async ({ page }, info) => {
    await entrarComo(page, 'jefe_almacen')
    await page.goto('/wms/alertas')
    await page.getByTestId('alerta').filter({ hasText: 'L-TRASLADO' }).getByTestId('alerta-ver-mapa').click()
    await expect(page).toHaveURL(/\/wms\/almacen\?.*buscar=L-TRASLADO/)
    if (!esTelefono(info)) await expect(page.getByTestId('mapa')).toBeVisible()
  })

  test('los enlaces de las entradas (lista, alertas, búsqueda) no dan "No encontramos eso"', async ({ page }) => {
    await entrarComo(page, 'jefe_almacen')
    await page.goto('/wms/entradas')
    const hrefs = await page.$$eval('a[href^="/wms/entradas/"]', (as) => [...new Set(as.map((a) => a.getAttribute('href')!))].filter((h) => !h.endsWith('/nuevo')))
    expect(hrefs.length).toBeGreaterThan(2)
    for (const h of hrefs) {
      await page.goto(h)
      await expect(page.getByTestId('titulo-solicitud')).toBeVisible()
    }
  })

  test('Sandra resuelve los faltantes y cierra el expediente', async ({ page }, info) => {
    await entrarComo(page, 'asistente_dt')
    await page.goto('/wms/expedientes')
    await capturar(page, info, 'expedientes', { completa: true })
    await page.getByTestId('fila-expediente').filter({ hasText: 'OC-DEMO-0001' }).click()
    await expect(page.getByTestId('documentos-expediente')).toContainText('Acta de Recepción')
    await expect(page.getByTestId('cerrar-expediente')).toBeDisabled()
    for (let i = 0; i < 10; i++) {
      const b = page.getByTestId('resolver-faltante').first()
      if (!(await b.count())) break
      await b.click()
      await page.waitForTimeout(400)
    }
    await expect(page.getByTestId('sin-faltantes')).toBeVisible()
    await capturar(page, info, 'expediente', { completa: true })
    await page.getByTestId('cerrar-expediente').click()
    await expect(page.getByTestId('expediente-cerrado')).toBeVisible()
  })

  test('la búsqueda universal encuentra la OC y el acta', async ({ page }) => {
    await entrarComo(page, 'jefe_almacen')
    await page.goto('/wms/entradas')
    await page.getByTestId('abrir-busqueda').click()
    await page.getByRole('dialog', { name: 'Búsqueda' }).locator('input').first().fill('OC-DEMO-0001')
    await expect(page.getByRole('dialog', { name: 'Búsqueda' })).toContainText('Órdenes de compra')
    await expect(page.getByRole('dialog', { name: 'Búsqueda' })).toContainText('OC-DEMO-0001')
  })

  test('el inicio avisa a cada rol lo suyo', async ({ page }) => {
    await entrarComo(page, 'direccion_tecnica')
    await expect(page.getByTestId('atencion')).toContainText('Alertas abiertas')
    await cambiarRol(page, 'asistente_dt')
    await expect(page.getByTestId('atencion')).toContainText('Actas organolépticas por llenar')
    await expect(page.getByTestId('atencion')).toContainText('Cantidades físicas por registrar en Compras')
    await cambiarRol(page, 'jefe_almacen')
    await expect(page.getByTestId('atencion')).toContainText(/Recepciones|Mercadería por llegar/)
  })
})
